version: '3.5'

services:

  nginx:
    image: nginx:1.13.12
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf:/etc/nginx/conf
      - ./public:/var/www/html
    restart: always