version: '3'

services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    image: yuttasakcom/proxy:1.0.0
    container_name: proxy
    ports:
      - "80:80"
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: yuttasakcom/web:1.0.0
    container_name: nginx
    restart: always

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    image: yuttasakcom/php:1.0.0
    container_name: php
    restart: always

  