version: '3.5'

services:

  nginx:
    build: .
    image: yuttasakcom/nginx:1.13.12
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/nginx/conf/nginx.conf
      - ./conf/site:/nginx/conf/site
    restart: always