version: '3.5'

services:

  nginx:
    image: nginx:1.13.12
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./public:/var/www/html
      - ./files:/data/files
    restart: always