version: '3.5'

services:

  nginx:
    build: .
    image: yuttasakcom/lua-resty-upstream-healthcheck:1.0.0
    volumes:
      - ./conf/nginx.conf:/nginx/conf/nginx.conf
      - ./conf/site:/nginx/conf/site
    ports:
      - "80:80"
    restart: always

  web1:
    image: openresty/openresty:alpine
    volumes:
      - ./web1/conf.d:/etc/nginx/conf.d
      - ./web1/html:/var/www/html
      - ./web1/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  web2:
    image: openresty/openresty:alpine
    volumes:
      - ./web2/conf.d:/etc/nginx/conf.d
      - ./web2/html:/var/www/html
      - ./web2/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  web3:
    image: openresty/openresty:alpine
    volumes:
      - ./web3/conf.d:/etc/nginx/conf.d
      - ./web3/html:/var/www/html
      - ./web3/nginx.conf:/etc/nginx/nginx.conf
    restart: always